### ISSUE TITLE
Add color information in elemental analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#104]

**Comment by kjappelbaum** [comment]
I do not know if you want to record it as coordinates in some color space. But it this is the case, then it might be neat to have a option to convert between different colorspaces, e.g., using https://github.com/colorjs/color-space

**Comment by lpatiny** [comment]
In this case it is really very basic information

![image](https://user-images.githubusercontent.com/1484241/94192450-421ab580-feaf-11ea-980a-7b562cb3b994.png)

In the visualizer we have couple of basic color methods: https://github.com/NPellet/visualizer/blob/master/src/src/util/color.js

and in image-js we use an alternative package: https://github.com/swiftcarrot/color-fns#readme but indeed you package is much more general. @kjappelbaum If you have some nice packages to advice you may directly contribute to https://github.com/cheminfo/awesome/settings/access
