### ISSUE TITLE
Update documentation of PXRD prediction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#128]
@kjappelbaum 

Could you edit the yellow box in the prediction layer to explain what is being done during this prediction from CIF file ?

![image](https://user-images.githubusercontent.com/1484241/95302813-bdeb0980-0882-11eb-9e61-dde4cf4ac6d0.png)

**Comment by kjappelbaum** [comment]
![Screen Shot 2020-10-07 at 10 32 10](https://user-images.githubusercontent.com/32935233/95307064-78c9d600-0888-11eb-90b2-36c7118a303d.png)

ok like that with you?

**Comment by lpatiny** [comment]
Perfect thanks.

BTW I added 3D structure if you click on a CIF

![image](https://user-images.githubusercontent.com/1484241/95592080-6f876780-0a48-11eb-866f-c84a2d6635b1.png)
