### ISSUE TITLE
add "about" on cheminfo.org and/or eln

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#133]
feedback from some users is that it is hard to understand for someone that hasn't been introduced to the sites, and that there should be probably some basic "about" like openBIS has https://openbis.ch/index.php/openrdm-swiss/ to let new potential users know why they might want to give the cheminfo tools/c6h6 a try. 

- [ ] citation on the c6h6.org home view should probably be selectable or even a link.
- [ ] maybe the Google Docs for the Help on the Home view can have some more basic information about the ELN and its philosophy ...
- [X] maybe add "about" on cheminfo.org  (maybe describe also different use-cases: self-hosting based on the roc-eln-docker [1] or using directly c6h6) 
- [ ] maybe make somewhere a list of papers that already used the ELN and/or cheminfo tools 
- [X] add some contact information in central place (either the google groups, a form or a email)

A simple wordpress site like http://www.aiida.net/ could do it.  

[1] I hope to add the kubernetes manifest / helm chart soon

**Comment by lpatiny** [comment]
Also related to https://github.com/cheminfo/eln.epfl.ch/issues/11

**Comment by kjappelbaum** [comment]
I think another easy thing one could try to address, is to try to bring the ELN into some of the compilations like 

- [ELN comparison grid](https://datamanagement.hms.harvard.edu/electronic-lab-notebooks) by Harvard Biomedial Data.
- [ELN guidance](https://www.gurdon.cam.ac.uk/institute-life/computing/elnguidance) by the Gurdon institute of the University of Cambridge.
- [Comparison of ELNs](https://github.com/Labii/comparison-of-best-electronic-lab-notebook) by the Labii ELN.
- [List of ELNs](https://en.wikipedia.org/wiki/List_of_electronic_laboratory_notebook_software_packages) on Wikipedia.

**Comment by kjappelbaum** [comment]
(I mention those as I'm working a bit on https://github.com/neo-chem/awesome-chemical-data)

**Comment by kjappelbaum** [comment]
The other nice thing if there would be such a website is that one would then be eligible to apply to

- [NumFocs](https://numfocus.org/projects-overview)
- [Google summer of code](https://summerofcode.withgoogle.com/archive//[Google season of docs](https://developers.google.com/season-of-docs/) 
...

**Comment by kjappelbaum** [comment]
@lpatiny do you have toc images or other images we're allowed to share for your papers such that we can put them on https://cheminfo.github.io/eln.epfl.ch/publications/?

**Comment by lpatiny** [comment]
@kjappelbaum Need to check for the images but where should I add the list of interesting publications ? I have them in Mendeley and here after you see a selection of the publications in bib format.

But maybe you have a format that allows to export them directly from Mendelay ?

[eln.epfl.ch.bib.zip](https://github.com/cheminfo/eln.epfl.ch/files/5728552/eln.epfl.ch.bib.zip)

**Comment by kjappelbaum** [comment]
bib is fine, will give it a look. and add them to https://cheminfo.github.io/eln.epfl.ch/publications/

**Comment by kjappelbaum** [comment]
i think this is now also done (at least in rough form)
