### ISSUE TITLE
add pxrd database matcher to pxrd view

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#135]
- [ ] Include a the current prototype for MOFs in the webservice 
- [ ] this then allows to start developing a view 
- [ ] look into downloading COD

**Comment by lpatiny** [comment]
I copied an existing project and started to change it:
https://github.com/cheminfo/docker-cod/ (it is private for now but you have access to it). After cleanup we will force push to clean git history.
The idea is to rsync COD and import it in mongo while calculating on the way some data.
In mongo we could have different representation of the data (compressed by NN for example).
We could also plan importation of PXRD without CIP files.
If you have some time to contribute you are welcome !

**Comment by kjappelbaum** [comment]
ok, will try to retrain the model with the COD on the weekend

**Comment by kjappelbaum** [comment]
maybe a simple full text search that pulls up the cif and then runs the prediction can be another neat application

**Comment by kjappelbaum** [comment]
Database lookup is implemented.
