### ISSUE TITLE
TEM/SEM enhancement - image analysis

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#14]
- nm/px change should update table and units should be in table header 
- maybe offer option to set scale manually (by measuring the scale) 
- in some nano regulations (Nanoreg) additional particle shape parameters such as Feret, Roundness are required (https://www.sympatec.com/en/particle-measurement/glossary/particle-shape/#, http://portal.s2nano.org:8282/files/TEM_protocol_NANoREG.pdf)

**Comment by lpatiny** [comment]
The pixel size management has been improved. We also added annotations. Tips will appear for new users and you may click on the help button to get more information.

![image](https://user-images.githubusercontent.com/1484241/89895655-74f93a80-dbdc-11ea-9467-d6f92845018e.png)

Please when there are different topics create different tickets.

**Comment by lpatiny** [comment]
@kjappelbaum  New properties for ROIs should be implemented on the 'legacy' branch of image-js.

It should probably be inspired by the following code:

https://github.com/image-js/image-js/blob/457696e9f38e1ec0aaa5d0b1335dbba447f03aa4/src/image/roi/Roi.js#L224-L237

We use a 'getter' so that the property is calculated on the fly if required.

**Comment by kjappelbaum** [comment]
I will look into the fractal dimension. 

A simple algorithm seems to be to count the number of filled in bins in a 2D histogram for varying bin widths and then fit this.

**Comment by lpatiny** [comment]
@kjappelbaum Could you open a new issue for this specific enhancement ? Otherwise we will have a never ending open issue.

**Comment by kjappelbaum** [comment]
I think this issue has nothing left that needs to be done. Most things from the norm are implemented, I will open an issue for me to go through the docs.
