### ISSUE TITLE
Isotherm: list of gas

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#141]
@kjappelbaum  list of gas

@lpatiny : check the format for the select button

**Comment by kjappelbaum** [comment]
CO2, water, methane for now.

I'm still worried a bit though that the full format we have now will have issues with multicomponent isotherms.

**Comment by kjappelbaum** [comment]
@lpatiny could you remind me how we can create the jpaths according to https://github.com/cheminfo/data_schema/blob/master/schema/sample/spectra/isotherm.md such that we can show temperature gas in the table in the view?

**Comment by kjappelbaum** [comment]
<img width="1008" alt="Screen Shot 2020-12-14 at 22 26 37" src="https://user-images.githubusercontent.com/32935233/102137644-702ee680-3e5b-11eb-80c5-9bcfa88caff6.png">
 
implemented.
