### ISSUE TITLE
Unit for temperature in °C

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#143]

**Comment by kjappelbaum** [comment]
do you mean that i should change something here https://github.com/cheminfo/isotherm-analysis/blob/027aefa0ac08197008dcf6c2c1962afd395cfefe/src/from/fromIGA.js#L198

**Comment by kjappelbaum** [comment]
check that unit is the jcamp

**Comment by kjappelbaum** [comment]
probably fixed.
