### ISSUE TITLE
Adjust cell parameter for PXRD prediction

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#147]

**Comment by kjappelbaum** [comment]
For the changes of the cell parameters it is probably good to also have visual feedback, so we would also need to change the parameters for the cell that is shown in the JMol applet

**Comment by kjappelbaum** [comment]
and if we anyhow do this, I wonder if we need a special API endpoint for that

**Comment by kjappelbaum** [comment]
otherwise, the API can also return a new cif

**Comment by kjappelbaum** [comment]
so https://github.com/cheminfo-py/xrd-tools now also has an endpoint that accepts a, b, c, alpha, beta, gamma

**Comment by kjappelbaum** [comment]
implemented
