### ISSUE TITLE
Upload for XRPD from sample/spectra view 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#15]

**Comment by kjappelbaum** [comment]
Hopefully addressed here https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F01782a99f2295c1dd86b72e34d2d5477%2Fview.json

**Comment by kjappelbaum** [comment]
@lpatiny i understood that it looks always at https://couch.cheminfo.org/cheminfo-public/ for these views and I did not find a way to make it use a local url (e.g., if I go to `on-tabs` and then create a new view there and get the id of this view). The question is then how can I save a view at ttps://couch.cheminfo.org/cheminfo-public/?

**Comment by lpatiny** [comment]
We need to discuss about this because the goal is not to import all kind of files from the sample pages. There would be too many cases to deal with.

For specific format we upload them from the specific view like we did with TGA.

**Comment by kjappelbaum** [comment]
Actually, I think it would be a great feature to have everything summarized on one page (the request for Xray/TGA/Isotherm ... on one page of one user was actually the reason I opened this issue). 

I agree that this can be easily confusing though and in the longer run we might want to look either having a "materials science" and "organic chemistry" flavor or group the spectra better.

**Comment by kjappelbaum** [comment]
I think this can be closed after our discussion. For how to add views, there's a PR here https://github.com/cheminfo/roc-eln-docker/pull/26.
