### ISSUE TITLE
Update EA form 

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#164]
-        Le formulaire avec QR code a un titre incorrect….c’est marqué « XRay sample submission form » au lieu de « EA sample submission form »
-        Nous rencontrons beaucoup de problèmes lié au fait que les utilisateurs ne sèchent pas correctement leurs échantillons et en plus nous le donnent dans un énorme tube en verre. Au niveau du texte des instructions en bas du formulaire, est-ce que tu peux rajouter en gras et rouge la phrase « must be powdered and well dried ». Et corriger Elemantal en Elemental dans la première phrase ?
-        Rajouter la phrase « Samples should be given as a fine and homogeneous powder and placed in the dedicated glass micro tubes available at the ISIC chemical store.

**Comment by kjappelbaum** [comment]
you fixed all except for "Et corriger Elemantal en Elemental dans la première phrase ?" it is done in the attached view.

[ea_form.txt](https://github.com/cheminfo/eln.epfl.ch/files/5896027/ea_form.txt)

**Comment by lpatiny** [comment]
Done
