### ISSUE TITLE
Determine possible MF from elemental analysis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#187]

**Comment by kjappelbaum** [comment]
is it basically https://www.cheminfo.org/Chemistry/Elemental_analysis/Find_MF_composition_from_EA/index.html?

**Comment by lpatiny** [comment]
There are 2 projects in fact. One was to find an molecular formula that match exactly an elemental analysis and this is the view you found.

There is another project that finds reasonable MF.  I added it in the elemental analysis view:

![image](https://user-images.githubusercontent.com/1484241/100602470-38c12580-3304-11eb-91a5-3c8f749595fc.png)

And there is a new package that calculates this

https://github.com/cheminfo/mass-tools/tree/master/packages/mf-from-ea
