### ISSUE TITLE
Search using modification date, creation and users

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#19]
currently, one could in principle use the operators to search for dates, but it is not practical as  it compares against the number of milliseconds since 1 January 1970 00:00:00 UTC ... but maybe we could catch this case in the `smart-array-filter`. 

also, in the TOC the creation date and the modification date is not stored though those can be quite handy for the search.

**Comment by kjappelbaum** [comment]
@lpatiny i couldn't find where `sampleToc` is created / how we can move stuff there. Could you maybe send me here a pointer?

**Comment by lpatiny** [comment]
Instead of emitting in the view epoch we can change by:

new Date(epoch).toISOString().replace(/\..*/,'')

I checked and it is compatible with the current homepage view and it would allow to search by the smart array filter (I think)

**Comment by kjappelbaum** [comment]
I guess I do not follow you completely, but I guess for convenient search one would need some kind of number. The one could try to search for something like `creationDate:20200601..20200730`. (At least this was the idea of the PR).

**Comment by kjappelbaum** [comment]
Implemented by Luc.
