### ISSUE TITLE
check if mongodb for xrd.cheminfo.org is running

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#202]
I tried to implement the lookup in the view but it seems to me that the mongodb is not running?

**Comment by lpatiny** [comment]
It is not
```
xrdtools_mongodb_1       docker-entrypoint.sh mongod      Exit 14                           
xrdtools_xrd-predict_1   /bin/sh -c uvicorn xrd_too ...   Up        0.0.0.0:12209->12209/tcp
```

`Some services (mongodb) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.`
