### ISSUE TITLE
token view broken

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#238]
attached the fixed version. Can we move this in production? I'm working on some integration with other services like AiiDA lab and for this it can be pretty convenient. 

[tokenView.json.txt](https://github.com/cheminfo/eln.epfl.ch/files/5966342/tokenView.json.txt)

**Comment by lpatiny** [comment]
@kjappelbaum You have now access to the view. Take care that it works on c6h6 and eln.

**Comment by kjappelbaum** [comment]
fixed.
