### ISSUE TITLE
tga drag and drop broken 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#239]
tried to drag and drop the txts

**Comment by kjappelbaum** [comment]
also toogling between the different temperature vs. mass and vs. time is buggy. 
All spectra should have a time trace but it does not show up for all

**Comment by kjappelbaum** [comment]
the reason is that the drag and drop wants to automatically convert to jcamp which does not work for the perkin elmer txts ... will fix this

**Comment by kjappelbaum** [comment]
and if tracking info is disabled it still shows

**Comment by lpatiny** [comment]
Which view are you testing ? The one in development on my.cheminfo ? Because the one on eln.epfl.ch is quite old.

**Comment by kjappelbaum** [comment]
fixed.
