### ISSUE TITLE
stock enhancements

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#240]
When preparing for the Zoom session i run into these.

@lpatiny if you give me the rights for the views I can take care

- [x] show quantity in table in stock view 
- [x] make last three columns larger in stock view 
- [x] `<p><br></p>` is not a good default for the description 
- [x] Make the supplier, quantity, purity fields also editable from the "sample/stock" view. 
- [x]  "Print location" in stock view broken (cannot select printer because `locationFormats` is empty)

**Comment by lpatiny** [comment]
@kjappelbaum where is this <p><br></p> as default description ?

**Comment by kjappelbaum** [comment]
it was here. But it seems this got fixed but the last three columns are still quite small 

![Screen Shot 2021-02-15 at 14 23 09](https://user-images.githubusercontent.com/32935233/107951910-5748cb80-6f99-11eb-87a9-0312a3e0378f.png)
