### ISSUE TITLE
tga view drag and drop 

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#253]
deal with the txt

@lpatiny i think i do not have the rights (my gmail account kevin.m.jablonka)

**Comment by lpatiny** [comment]
You have the right now. This view is still a work-in-progress with the new structure (and a lot of code in visualizer-helper). Not sure it is fully functional.

**Comment by kjappelbaum** [comment]
fixed with https://github.com/cheminfo/tga-spectrum/commit/2a1497bad1bfad8d3a54f05d58cb331903b5081d and also used in production on eln.epfl.ch
