### ISSUE TITLE
molecular formula parsed incorrectly

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#274]
![image](https://user-images.githubusercontent.com/32935233/110775703-83d1c980-825f-11eb-8daa-3cb5846b5802.png)

Cu(NO3)2(H2O)3 is parsed as CuN2O6.3(H2O) when reagent is entered in the reagent table

**Comment by kjappelbaum** [comment]
could reproduce bug with CAS number 10031433 in the eln.epfl.ch deployment

**Comment by kjappelbaum** [comment]
the information is correct in ChemExper

**Comment by kjappelbaum** [comment]
just adding spaces around the "." does not work as it really could be fractional ...

**Comment by kjappelbaum** [comment]
one could extract the mf from the molfile

**Comment by lpatiny** [comment]
It is the source of the data (chemexper) that was wrong and is now fixed.

**Comment by kjappelbaum** [comment]
i still think that this might be a more general issue and not only for this case.

**Comment by kjappelbaum** [comment]
e.g., it is still here https://www.chemexper.com/search/reference/json2/quick/6018-89-9

**Comment by lpatiny** [comment]
But again it would rather be correcting the MF in ChemExper. No chemical supplier provides a molecular formula the way a chemist things about and I think this would be the way to go.
The renderer is much better for MF: https://zakodium.github.io/react-mf/?path=/story/mf--charged-salt and could be added in the visualizer.

**Comment by kjappelbaum** [comment]
if you have a way to fix all these cases in Chemexper we should certainly do it. Otherwise i would sacrifice beauty for correctness https://github.com/cheminfo-js/visualizer-helper/pull/35

**Comment by kjappelbaum** [comment]
![Screen Shot 2021-03-11 at 13 43 21](https://user-images.githubusercontent.com/32935233/110789058-c00d2600-826f-11eb-92e2-be6238969724.png)

and also the React renderer fails if there is no space as it is ambiguous

**Comment by lpatiny** [comment]
Reference database was fixed

![image](https://user-images.githubusercontent.com/1484241/111025389-0a171880-83e4-11eb-84f2-0ce8dba2110f.png)
