### ISSUE TITLE
make Zenodo exports fully functional and test it

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#31]
i would like to put as a goal that the next experimental paper that comes from our group should have the full SI on Zenodo.

**Comment by kjappelbaum** [comment]
then, we should also think about what is the most convenient/user friendly way to link to other databases. E.g., one might have simulations that are deposited on materials cloud and wants to link them to the correct entries from the ELN.

**Comment by kjappelbaum** [comment]
@lpatiny If i understood correctly it was some missing implementation for the Zenodo API in roc?

**Comment by lpatiny** [comment]
I think that the sandbox is working correctly so it is rather changing the API key and the URL to submit in the real database. But you may try freely to use the sandbox

**Comment by kjappelbaum** [comment]
just tested it and will add here the issues i found for reference 
- [ ] works only if there is a molecular formula, I think this is to strict. In materials science this might not be always well defined and one still might want to export the spectra
- [ ] `https://www.cheminfo.org/flavor/zenodo` needs to be updated to display spectra other than NMR 
- [ ] Allow to submit to "real" Zenodo and not only sandbox, but still keep the sandbox option. I.e., the case when the checkbox is not ticked should work

**Comment by kjappelbaum** [comment]
[ ] Also error should bubble up. I now tried some entries with molecular formula and it failed again for unclear reasons.

**Comment by kjappelbaum** [comment]
![photo_2020-09-16 14 31 15](https://user-images.githubusercontent.com/32935233/93337324-4993ec00-f829-11ea-85ab-10d73e058f53.jpeg)
submitted many entries at once seems to make issues

**Comment by kjappelbaum** [comment]
- [ ] custom captions do not appear in the final entry?

**Comment by kjappelbaum** [comment]
- [ ] export corresponding reactions

**Comment by kjappelbaum** [comment]
closing as I opened separate tickets for each issue
