### ISSUE TITLE
maybe the visualizer modules should remain fixed

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#32]
in the TGA view if the module with the TGA filters is moved into direction of the spectrum it cannot moved back 
(some users started changing the size of the modules to make them fit on their screens)

**Comment by lpatiny** [comment]
Indeed it can not be moved back if the size of the screen is not big enough. This means that the visualizer (https://github.com/npellet/visualizer/) prevents you to draw a module outside the screen

You can always virtually increate your screen by reduce the scale of the font in the browser

![image](https://user-images.githubusercontent.com/1484241/90225221-3c8e7200-de11-11ea-97eb-c08be4ace438.png)

And this should work.

Many views are designed for HD resolution.
