### ISSUE TITLE
Display meta information in TOC

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#53]

**Comment by kjappelbaum** [comment]
I still think that the owner and dates (https://github.com/cheminfo/roc-eln-config/pull/13) would be useful to have.

**Comment by lpatiny** [comment]
Ok I will add the owner and date in format "YYYY-MM-DD" in epfl toc

https://github.com/cheminfo/eln.epfl.ch/issues/54

**Comment by lpatiny** [comment]
![image](https://user-images.githubusercontent.com/1484241/91970305-be3e3500-ed17-11ea-8138-15d165153f8d.png)
