### ISSUE TITLE
Add searchable owner and date in toc

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#54]

**Comment by lpatiny** [comment]
Need to improve smart-array-filter to allow to search for > and < on strings

https://github.com/cheminfo-js/smart-array-filter/issues/11

**Comment by kjappelbaum** [comment]
BTW, for the date I thought of https://github.com/cheminfo/eln.epfl.ch/issues/19#issuecomment-666235235 to avoid the need for < and > on strings

**Comment by lpatiny** [comment]
4 points were done:
- new version of smart-array-filter: https://github.com/cheminfo/smart-array-filter and update the README. All those features are available in the quick search in the homepage
- release a new version of the visualizer: https://github.com/NPellet/visualizer/commit/d8feda32a8d3bee13a974a4dabc6445d167c4a85
- add @epfl modified and created in the toc (format XXXX-YY-ZZ). This format is compatible with javascript so you can directly do `new Date('2020-10-01')` and easy to create with `new Date().toISOString().substring(0,10)`
- add @epfl the owner in toc
