### ISSUE TITLE
Does not load with Chrome on iPad

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#6]

**Comment by lpatiny** [comment]
This is a known bug and the same reason why eln.epfl.ch is not working on Safari but we never found a simple solution to solve it. (chrome on iOs is using Safari engine for rendering as far as I know).

If you have a solution it is welcome !

**Comment by kjappelbaum** [comment]
Oh, I didn't know that Chrome on iOS also uses webkit. 
There are indeed a lot of bug reports for `WebKitBlobResource error 1` out there. After my exam, I'll see if I can make sense of it.

**Comment by kjappelbaum** [comment]
seems to be https://jsfiddle.net/24FhL/

**Comment by kjappelbaum** [comment]
based on https://bugs.webkit.org/show_bug.cgi?id=197441 and https://stackoverflow.com/questions/37817591/unable-to-download-pdf-blob-url-on-safari this seems to mean that one needs to open a new tab for the blobs. But as described in the stackoverlow, it is a bit unclear what happens with adblockers.

**Comment by kjappelbaum** [comment]
Using 
```
  var configJson = JSON.stringify(config);
            const blob = new Blob([configJson], { type: 'application/json' })
            let url = window.URL.createObjectURL(blob);
            window.open(url, "_blank");
            if (!configs.has(configJson)) configs.set(configJson, url);
            config = configs.get(configJson);
```
In line 32150 does no longer raise an error but it does not stop loading.

**Comment by kjappelbaum** [comment]
Just unpinning the tab didn't help apparently

**Comment by kjappelbaum** [comment]
Changing the timeout might be a promising way https://github.com/kennethjiang/js-file-download/pull/63

**Comment by targos** [comment]
we never revoke the URLs in the visualizer on tabs

**Comment by lpatiny** [comment]
Without known solution I close this ticket and add a message in case the visitor tries to access using Safari (or an iPad).
