### ISSUE TITLE
Filter particules based on presence of internal holes

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln.epfl.ch#63]
Should calculate a criteria that calculates the percentage of surface that is inside the ROI and not part of the ROI (a hole in the ROI).

@kjappelbaum  any idea for the name for this property that would be the ratio of surfaces ?

**Comment by kjappelbaum** [comment]
As far as we know, there is no name for this that is widely used. Something like "fillingfactor" might work though.

**Comment by lpatiny** [comment]
Implemented. New parameter: `fillRatio`
