### ISSUE TITLE
rolling mean/median filters

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#65]
for the baseline correction package we basically have a rough version of a running median filter (we might generalize it more and add more options for the ends).  

We might consider also offering the running mean as a smoother in the filter dropdown for all spectra.

**Comment by lpatiny** [comment]
Implemented in ml-spectra-processing

- https://github.com/mljs/spectra-processing/pull/21
- https://github.com/mljs/spectra-processing/pull/19
- https://github.com/mljs/spectra-processing/pull/24
