### ISSUE TITLE
Bug in XRD view

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#67]
The upload for `xy` and `brml` did not work and the labeling of the drag and drop was not correct. 

The attached view should work. I also did some renaming XRD -> PXRD as I think this module will always only work for powder diffraction patterns. Maybe we should do the renaming also on the home view. 

[pxrd_view.txt](https://github.com/cheminfo/eln.epfl.ch/files/5184168/pxrd_view.txt)

**Comment by lpatiny** [comment]
In production, Thanks !
