### ISSUE TITLE
Make view for the isotherms

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#87]
- the most relevant parser should be implemented: https://github.com/cheminfo/isotherm-analysis
- we could also calculate some theoretical properties: https://github.com/cheminfo/poreprober

it is not clear to me how we should make the view, maybe we can just start to show x/y of the jcamps.

**Comment by kjappelbaum** [comment]
@lpatiny if you could give me the rights for a barebone view for the isotherms it would be great

**Comment by lpatiny** [comment]
The general view has been created and we should now make many tickets with the different features to implement.
